### PR TITLE
Update rails helper to support specifying session role

### PR DESCRIPTION
**Pull request by mascott**
While updating KnowledgeAssessment to support roles I ran into an issue with our default 'user' role. The only roles KnowledgeAssessment currently supports are 'admin' and 'student'. I've updated the gem to default to admin as well as updating the `with_valid_maestro_session` method to support an optional `role` parameter.

I'm not sure how we handle versioning on this gem so I've left this change unversioned.

### CODE REVIEW

**Comment by fuudstamps** [comment]
@mascott  We just `bundle update maestro` for the projects using it (Maestro, KA and DummyApp) after the PR gets merged into Master

**Comment by mascott** [comment]
Perfect. Thanks @fuudstamps!

**Comment by jasonpaluck** [comment]
I'm not sure where the role `student` comes from, but that's not what should be supporting. The roles are `user` and `admin`, since `student` isn't appropriate for adult learners.

**Comment by jasonpaluck** [comment]
@mascott I searched all the code in KA, and there is no reference to `student`. Not sure if you were trying to add that in a local branch, but that's not an appropriate label. Please keep them, as in all our apps, as `user` and `admin`.

**Comment by aspencer8111** [comment]
@jasonpaluck I think he used `student` bc that is how it was labeled in this pivotal story. https://www.pivotaltracker.com/story/show/118831077 . I added it that way after discussing the roles coming to us from the RV side with Smitha. Regardless, we can spin up a quick user story to change it

**Comment by jasonpaluck** [comment]
That's because RV chose to use the term Student in the LMS. Definitely no Bueno for the other business units or KA. Let's keep all references to roles constant across our apps, they can send User when they want their Student role.

**Comment by mascott** [comment]
Ah, good to know. Thanks for the clarification.

**Pull request merged**
